### ISSUE TITLE
[Bug] Unable to build the template, not even with a fresh install 

### ISSUE THREAD

**Issue by samoritano** [creativetimofficial/ct-argon-design-system-pro-react#2] opened 2021-02-05 13:22 UTC
### Version
1.0.0
### Reproduction link
http://localhost
### Operating System
Ubuntu 20.04 and Macos
### Device
Terminal
### Browser & Version
-
### Steps to reproduce
Just download the fresh repo and try to build it with
npm run build
### What is expected?
We've been implementing a dashboard for a few days, and we only used the live reload with 'next start'. 
After that, we tried to build the repo and we receive this message:

> Build error occurred
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/sam/workspace/code/mediterranea-frontend/node_modules/list.js/src/utils/events.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/sam/workspace/code/mediterranea-frontend/node_modules/list.js/src/index.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  type: 'ReferenceError'
}

We thought we did something wrong, but after downloading a fresh copy of the template, we are getting the same message.

### What is actually happening?
.

---

**Comment by sajadevo** [comment] 2022-08-25 12:42
Hi @samoritano,

The issue is fixed on the latest version of the product.

Regards,
Sajad

**Closed as completed by sajadevo** 2022-08-25 12:42 UTC
